### ISSUE TITLE
[Rift] Suggestion: Add Option for "is typing..."

### ISSUE THREAD

**Issue by Menteroth** [zephyrkul/FluffyCogs#54]
Any possibility to add an option where you can enable "is typing..." to messages sent through the rift?

So when you hit enter to send the message it says the bot is typing for like 3 seconds and then sends the message. So it doesn't look like it's appearing out of nowhere.

**Comment by zephyrkul** [comment]
This is a feature I've thought about before but put off on implementing due to the below.

The best method for handling this would be to listen for [`typing`](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_typing) events. However, the core Red devs have stated that they intend to disable the typing intent by default, which would remove the bot's ability to listen for those events. I might throw in the event anyway, since it's quite simple to do, but be aware that future versions of Red likely won't support typing events without passing a CLI flag to re-enable the typing intent.

Your method (putting an artificial 3-second delay between the message being received and the message being forwarded) would result in undesirable race conditions if someone changes that message (edits / deletes) during those 3 seconds, so I won't be implementing that method.
